# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
# version: 2
# build:
#   os: ubuntu-22.04
#   tools:
#     python: "3.10"


# python:
#    install:
#    - requirements: ./package/docs/source/requirements.txt


# python:
#   install:
#     - method: pip
#       path: ./package/
#       extra_requirements: ./package/docs/source/requirements.txt
build:
  os: ubuntu-20.04
  tools: {python: "3.10"}
  jobs:
    pre_create_environment:
      - asdf plugin add poetry
      - asdf install poetry latest
      - asdf global poetry latest
      - poetry config virtualenvs.create false
    post_install:
      - cd package
      - poetry install
      - cd ..
