# This workflow will install Python dependencies and run tests

name: Python package

on:
  push:
    branches: [ "main", "luisaforozco-test-lint" ]
  pull_request:
    branches: [ "main", "luisaforozco-test-lint" ]

jobs:
  build:

    name: Build for (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install poetry
        poetry lock --no-update
        poetry install
    - name: Verify that we can build the package
      run: poetry build
    - name: Test with pytest
      run: poetry run pytest
  lint:
    name: Linting build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install poetry
          poetry lock --no-update
          poetry install
      - name: Check style against standards using prospector
        run: prospector
      - name: Check import order
        run: isort --check-only grainlearning --diff
