# This workflow will install Python dependencies and run tests

name: Python linter

on:
  pull_request:
    branches: [ "main"]

jobs:
  lint:
    name: Linting build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      # - uses: actions/cache@v3
      #   with:
      #     path: ${{ env.pythonLocation }}
      #     key: ${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}
      - name: Install dependencies
        run: |
          python -m pip install poetry
          # export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring #https://github.com/python-poetry/poetry/issues/3365
          # poetry cache clear --all .
          poetry install -E dev -E rnn -vvv
      - name: Check style against standards using prospector
        run: poetry run prospector
      - name: Check import order
        run: isort --check-only grainlearning --diff
